spring.application.name=rls
spring.redis.host=localhost
spring.redis.port=6379

rate-limiter.policies[0].api=/api/v1/test
rate-limiter.policies[0].limit=10
rate-limiter.policies[0].window-seconds=60
rate-limiter.policies[0].algorithm=FIXED_WINDOW

rate-limiter.policies[1].api=/api/v1/another
rate-limiter.policies[1].limit=5
rate-limiter.policies[1].window-seconds=30
rate-limiter.policies[1].algorithm=FIXED_WINDOW