spring.application.name=rls
spring.redis.host=localhost
spring.redis.port=6379

rate-limiter.policies[0].api=/api/v1/test-fixed-window
rate-limiter.policies[0].limit=10
rate-limiter.policies[0].window-seconds=60
rate-limiter.policies[0].algorithm=FIXED_WINDOW

rate-limiter.policies[1].api=/api/v1/another-fixed-window
rate-limiter.policies[1].limit=5
rate-limiter.policies[1].window-seconds=30
rate-limiter.policies[1].algorithm=FIXED_WINDOW

rate-limiter.policies[2].api=/api/v1/test-token-bucket
rate-limiter.policies[2].limit=5
rate-limiter.policies[2].window-seconds=1
rate-limiter.policies[2].algorithm=TOKEN_BUCKET

rate-limiter.policies[3].api=/api/v1/another-token-bucket
rate-limiter.policies[3].limit=10
rate-limiter.policies[3].window-seconds=2
rate-limiter.policies[3].algorithm=TOKEN_BUCKET

rate-limiter.policies[4].api=/api/v1/test-leaky-bucket
rate-limiter.policies[4].limit=6
rate-limiter.policies[4].window-seconds=3
rate-limiter.policies[4].algorithm=LEAKY_BUCKET

rate-limiter.policies[5].api=/api/v1/another-leaky-bucket
rate-limiter.policies[5].limit=10
rate-limiter.policies[5].window-seconds=8
rate-limiter.policies[5].algorithm=LEAKY_BUCKET

rate-limiter.policies[6].api=/api/v1/test-sliding-log
rate-limiter.policies[6].limit=6
rate-limiter.policies[6].window-seconds=3
rate-limiter.policies[6].algorithm=SLIDING_WINDOW_LOG

rate-limiter.policies[7].api=/api/v1/another-sliding-log
rate-limiter.policies[7].limit=10
rate-limiter.policies[7].window-seconds=8
rate-limiter.policies[7].algorithm=SLIDING_WINDOW_LOG

rate-limiter.policies[8].api=/api/v1/test-sliding-counter
rate-limiter.policies[8].limit=6
rate-limiter.policies[8].window-seconds=3
rate-limiter.policies[8].algorithm=SLIDING_WINDOW_COUNTER

rate-limiter.policies[9].api=/api/v1/another-sliding-counter
rate-limiter.policies[9].limit=10
rate-limiter.policies[9].window-seconds=8
rate-limiter.policies[9].algorithm=SLIDING_WINDOW_COUNTER